### PR TITLE
Update system_stats.py

### PR DESCRIPTION
**Pull request by NotShroudX97**

### CODE REVIEW

**Comment by niteshraj2310** [comment]
@NotShroudX97 bro really wtf

**Comment by NotShroudX97** [comment]
@NotShroudX97 Lel Surry xD 😂

**Comment by sahyam2019** [comment]
😶🤷

**Comment by niteshraj2310** [comment]
@sahyam2019 wat

**Comment by sahyam2019** [comment]
> @sahyam2019 wat

?

**Comment by NotShroudX97** [comment]
Beru Surry xD Me Nuub 🤦🏼‍♂️

**Pull request closed without merging**
