### PR TITLE
Chrome error phixd

### PR DESCRIPTION
**Pull request by niteshraj2310**
According to Docker

Signed-off-by: Nitesh <niteshraj231@outlook.com>

Everyone change in your config vars,
i.e. GOOGLE_CHROME_BIN =  /usr/bin/chromium-browser
to `GOOGLE_CHROME_BIN` = `/usr/bin/google-chrome`

### CODE REVIEW

**Comment by RoyalBoy69** [comment]
@niteshraj2310 Pro

**Comment by niteshraj2310** [comment]
@niteshraj2310 .all

**Comment by niteshraj2310** [comment]
@niteshraj2310 @all⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣

**Comment by niteshraj2310** [comment]
@niteshraj2310 hm

**Pull request merged**
