### PR TITLE
added .report cmd 😏😏

### PR DESCRIPTION
**Pull request by RoyalBoy69**

### CODE REVIEW

**Comment by sahyam2019** [comment]
@RoyalBoy69 Add help

**Comment by sahyam2019** [comment]
@sahyam2019 Don't add such emojis

**Comment by code-rgb** [comment]
> @sahyam2019 Don't add such emojis

🚬😏🎩 🏇👯‍♀️

**Comment by niteshraj2310** [comment]
@code-rgb gwad

**Pull request merged**
