### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by niteshraj2310**
Bump google-api-python-client from 1.8.0 to 1.10.0 🙂🙏

### CODE REVIEW

**Comment by abhinav6497** [comment]
@niteshraj2310 Bhaiya kidhar ho tum?

**Comment by sahyam2019** [comment]
@niteshraj2310 well why ..ig it will work

**Comment by niteshraj2310** [comment]
> @niteshraj2310 well why ..ig it will work
 
ayw dude 🙂👍

**Comment by abhinav6497** [comment]
@niteshraj2310 Kaha ho bro?

**Comment by HariadyAz** [comment]
@niteshraj2310 Test comment

**Comment by pWoLiAn** [comment]
> > @niteshraj2310 well why ..ig it will work
> 
> ayw dude 🙂👍

bhaag bc

**Comment by niteshraj2310** [comment]
@sahyam2019  

 bro lock this convo 🙂🙏

**Comment by sahyam2019** [comment]
Bakchodi na karo idhar

**Pull request closed without merging**
