### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by sks98765**

### CODE REVIEW

**Comment by abhinav6497** [comment]
@sks98765 Abbe saale😂
Uske repo me kyu kiya🤣

**Comment by sks98765** [comment]
Mereko b pata nhi ek bands ne bola not lagane k liye ye ye kar maine wahi
kiya bas baaki mai nhi janta bisi

**Comment by sks98765** [comment]
Bot*

**Comment by abhinav6497** [comment]
@sks98765 Are vo dockerfile khud ke repo me change kro😂

**Comment by sks98765** [comment]
Kaise karte h ? Mai nhi janta telegram do apna batata msg krta usme mai

**Comment by abhinav6497** [comment]
@sks98765 @abhinavshinde

**Comment by RoyalBoy69** [comment]
@sks98765 @RoyalBoy69

**Comment by sks98765** [comment]
@abhinav6497 dekh msg

**Comment by RoyalBoy69** [comment]
@sks98765 Mtlb comments

**Comment by sks98765** [comment]
@RoyalBoy69  bsdk tereko nhi bolra @abhinav6497 iski bolra telegram msg check kar

**Comment by RoyalBoy69** [comment]
@sks98765 Lol

**Comment by RoyalBoy69** [comment]
@RoyalBoy69 But gali kiu

**Comment by sks98765** [comment]
@RoyalBoy69  sry for gaali flow flow m nikal jata h

**Comment by RoyalBoy69** [comment]
@sks98765 @sks98765 pull request close kr

**Pull request closed without merging**
