### PR TITLE
Update admin.py

### PR DESCRIPTION
**Pull request by RoyalBoy69**

### CODE REVIEW

**Comment by niteshraj2310** [comment]
tf 🌚

**Comment by sahyam2019** [comment]
@RoyalBoy69 Yeh kis cheez ke liye hai 🤷

**Comment by sahyam2019** [comment]
@niteshraj2310 😶

**Comment by RoyalBoy69** [comment]
> tf

Kha ho sar bhot dino se dikhe nhi

**Comment by abhinav6497** [comment]
@sahyam2019 Sar wen coming on TG?

**Comment by sahyam2019** [comment]
@RoyalBoy69 Lol wtf

**Comment by niteshraj2310** [comment]
> @RoyalBoy69 Yeh kis cheez ke liye hai 🤷

wahi naa

**Comment by niteshraj2310** [comment]
> > tf
> 
> Kha ho sar bhot dino se dikhe nhi

ptaani kon hu mai kha hu mai 🙂🙄

**Comment by RoyalBoy69** [comment]
> @RoyalBoy69 Lol wtf

Try .lock all

**Comment by sahyam2019** [comment]
@RoyalBoy69 Nhi

**Comment by sahyam2019** [comment]
@sahyam2019 Comment lock kar dunga

**Comment by RoyalBoy69** [comment]
> @RoyalBoy69 Lol wtf

**Comment by sahyam2019** [comment]
@sahyam2019 Chat karna baand kar

**Comment by abhinav6497** [comment]
@niteshraj2310 .purge

**Comment by niteshraj2310** [comment]
> @niteshraj2310 .purge

wtf 🙁

**Pull request closed without merging**
